[workspace]
resolver = "2"
members = [
    "oddity-rtsp-protocol",
    "oddity-rtsp-server",
    "oddity-sdp-protocol",
]

# Specifying a workspace dependency is similar to package dependencies except:
# - Dependencies from this table cannot be declared as optional
# - features declared in this table are additive with the features from [dependencies]
[workspace.dependencies]
oddity-rtsp-protocol = { path = "oddity-rtsp-protocol" }
oddity-rtsp-server = { path = "oddity-rtsp-server" }
oddity-sdp-protocol = { path = "oddity-sdp-protocol" }
video-rs = { version = "0.5.0" }
